name: Saliency Test

on:
  push:
    branches: [ hardware_acceleration ]
  pull_request:
    branches: [ hardware_acceleration ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest test.py
