name: Saliency Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install -r requirements.txt
      # pip install pytest numpy opencv-contrib-python
      # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest test.py
  #  - name: Test with pytest
  #    run: |
  #     pytest
